version: "3"
services:
  scrapyrt:
    build: .
    command: scrapyrt -i 0.0.0.0 -p 9080
    ports:
      - "9080:9080"
    volumes:
      - .:/code
    working_dir: /code
    restart: always

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: bluewindow
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
